### PR TITLE
Add 7PK Taxonomy

### LINKED ISSUE #19: Seven Pernicious Kingdoms taxonomies
https://cwe.mitre.org/data/definitions/700.html

@yongyan-gh @shaopeng-gh

### PR DESCRIPTION
**Pull request by shaopeng-gh**
glad that CWE use the same xml schema , generated from the xml version.

7PK is the official short name as per website:
https://cwe.mitre.org/data/definitions/700.html
"The MITRE CWE team frequently uses "7PK" as an abbreviation for Seven Pernicious Kingdoms."

Fixes #19

### CODE REVIEW

**Comment by eddynaka** [comment]
>           "name": "CWE"

can you add the informationUri to CWE website?

---
In reply to: [905514550](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905514550) [](http://example.com/codeflow?ancestors=905514550)

---
In reply to: [905514550](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905514550) [](http://example.com/codeflow?ancestors=905514550)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Comment by eddynaka** [comment]
>           "name": "CWE"

It would fix: "/github/workspace/CWE_7PK_v4.5.sarif(7,19): warning SARIF2005: runs[0].tool.driver: The tool 'CWE' does not provide 'informationUri'. This property helps the developer responsible for addessing a result by providing a way to learn more about the tool."

---
In reply to: [905514550](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905514550) [](http://example.com/codeflow?ancestors=905514550)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Comment by eddynaka** [comment]
>           "name": "CWE"

maybe we should rename to CWE 7PK

---
In reply to: [905515608](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905515608) [](http://example.com/codeflow?ancestors=905515608)

---
In reply to: [905515608](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905515608) [](http://example.com/codeflow?ancestors=905515608)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Comment by eddynaka** [comment]
>           "name": "CWE"

Can you also review the driver.name from the other CWE sarif files that we generated before?

---
In reply to: [905515608](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905515608) [](http://example.com/codeflow?ancestors=905515608)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Comment by shaopeng-gh** [comment]
>           "name": "CWE"

I see we have like 
Name = "PCI DSS V3.1"
so I will check and change to similar names

---
In reply to: [905516218](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905516218) [](http://example.com/codeflow?ancestors=905516218,905515608)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Comment by shaopeng-gh** [comment]
>           "name": "CWE"

added

---
In reply to: [905514768](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905514768) [](http://example.com/codeflow?ancestors=905514768,905514550)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Comment by shaopeng-gh** [comment]
>           "name": "CWE"

updated all CWE sarif files

---
In reply to: [905698708](https://github.com/sarif-standard/taxonomies/pull/20#issuecomment-905698708) [](http://example.com/codeflow?ancestors=905698708,905516218,905515608)

---
Refers to: CWE_7PK_v4.5.sarif:8 in b50a017. [](commit_id = b50a01796e468341dd39b57da9baf1fc141f3e9e, deletion_comment = False)

**Review by eddynaka — APPROVED** [review]
:shipit:

**Pull request merged**
